### ISSUE TITLE
graphql-sequelize

### ISSUE THREAD

**Issue by ravishivt** [benawad/graphql-express-template#1]
I watched your video playlist for this repo and it's been very helpful.  Thanks for working on it.  A couple thoughts:

- The [YouTube playlist](https://www.youtube.com/playlist?list=PLN3n1USn4xllLHL29aVOJfgsEEpLCWnCk) is out of order.  The order of videos 1, 2, and 3 should be reversed.
- What are your thoughts on [graphql-sequelize](https://github.com/mickhansen/graphql-sequelize)?  It seems like a good fit since you are using sequelize.  I'm trying to evaluate whether to use it or not in my project.

I'm looking forward to your future videos, especially on how to leverage DataLoader and how to add more authorization/permission logic.

**Comment by benawad** [comment]
Hey, I'm glad the videos were helpful!

1. The order it shows for me is Installing..., Connect..., then Mutations... (which seems like the right order). How do you suggest it be ordered? Mutations..., Connect..., Installing...?

2. graphql-sequelize looks very interesting and seems like it would cut out a lot of boilerplate code. I  haven't tried it yet, but I will soon and then I can give you a better opinion on it.

3. DataLoader/Authorization/Permission stuff is coming soon and it's going to be really really cool :)

**Comment by ravishivt** [comment]
My bad on #1.  I linked the wrong playlist.  [This is the one](https://www.youtube.com/playlist?list=PLN3n1USn4xlnXfLBuSMFcYM5yei4oxdxB) I was referring to on being out of order.

**Comment by benawad** [comment]
You're totally right! Thanks for bringing this to my attention, I'll fix it.
