### ISSUE TITLE
Response Cookies Undefined

### ISSUE THREAD

**Issue by sjakati98** [benawad/graphql-express-template#10]
Hey!

So I am currently having the problem that within the resolvers file `res.cookie('token', token, options...)`, I do not believe that the cookies are being set. I suspect this because within my index file, the `req.cookies.token` is empty.

**Comment by benawad** [comment]
Check the network tab of Chrome, look for the request, and see if a SET-COOKIE header is being sent back

**Comment by sjakati98** [comment]
So I think I may have realized the issue. By using the graphiql client, I believe that the cookies are stripped from the request. This kinda makes it hard to set a cookie haha. Thanks for the tutorials and all the help!
