### ISSUE TITLE
Not really an issue just curious...

### ISSUE THREAD

**Issue by imranzaidi** [benawad/graphql-express-template#9]
https://github.com/benawad/graphql-express-template/blob/2b65cce4bc078d644452f0e2c6de74efa446f10e/models/index.js#L26

I searched the actual repo this is based on, express-example from the Sequalize docs. I can't see any usage of the Sequelize class instance being attached as property to db. When and where is this ever used?

**Comment by benawad** [comment]
Yeah, I haven't found a use for it

**Comment by imranzaidi** [comment]
Thanks, being new to Sequelize and GraphQL... I was wondering if I was missing something. Nice tutorials btw.
